
function controller_config(this_block)

  % Revision History:
  %
  %   18-May-2015  (17:09 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\javier\master-cll\koldo\controller.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('controller');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('in_signal');
  this_block.addSimulinkInport('ref_signal');
  this_block.addSimulinkInport('rst');

  this_block.addSimulinkOutport('out_signal');

  out_signal_port = this_block.port('out_signal');
  out_signal_port.setType('UFix_18_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('in_signal').width ~= 12);
      this_block.setError('Input data type for port "in_signal" must have width=12.');
    end

    if (this_block.port('ref_signal').width ~= 12);
      this_block.setError('Input data type for port "ref_signal" must have width=12.');
    end

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('ieee_proposed/standard_additions.vhd');
  this_block.addFile('ieee_proposed/numeric_std_additions.vhd');
  this_block.addFile('ieee_proposed/standard_textio_additions.vhd');
  this_block.addFile('ieee_proposed/std_logic_1164_additions.vhd');
  this_block.addFile('ieee_proposed/numeric_std_unsigned.vhd');
  this_block.addFile('ieee_proposed/fixed_float_types.vhd');
  this_block.addFile('ieee_proposed/fixed_pkg.vhd');
  this_block.addFile('ieee_proposed/float_pkg.vhd');
  this_block.addFile('ieee_proposed/env.vhd');
  this_block.addFile('controller.vhd');
return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

