
function contador_sinc_config(this_block)

  % Revision History:
  %
  %   29-Apr-2015  (17:31 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\javier\ise\contador_sinc.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('contador_sinc');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('clock');
  this_block.addSimulinkInport('direccion');

  this_block.addSimulinkOutport('cuenta_fin');
  this_block.addSimulinkOutport('cuenta');

  cuenta_fin_port = this_block.port('cuenta_fin');
  cuenta_fin_port.setType('UFix_1_0');
  cuenta_fin_port.useHDLVector(false);
  cuenta_port = this_block.port('cuenta');
  cuenta_port.setType('UFix_4_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('clock').width ~= 1);
      this_block.setError('Input data type for port "clock" must have width=1.');
    end

    this_block.port('clock').useHDLVector(false);

    if (this_block.port('direccion').width ~= 1);
      this_block.setError('Input data type for port "direccion" must have width=1.');
    end

    this_block.port('direccion').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../contador_sinc.vhd');

return;


