
function master_config(this_block)

  % Revision History:
  %
  %   29-Apr-2015  (18:36 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\javier\ise\master.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('master');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('modulo');
  this_block.addSimulinkInport('dir');

  this_block.addSimulinkOutport('cuenta_fin');
  this_block.addSimulinkOutport('cuenta');

  cuenta_fin_port = this_block.port('cuenta_fin');
  cuenta_fin_port.setType('UFix_1_0');
  cuenta_fin_port.useHDLVector(false);
  cuenta_port = this_block.port('cuenta');
  cuenta_port.setType('UFix_4_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('modulo').width ~= 3);
      this_block.setError('Input data type for port "modulo" must have width=3.');
    end

    if (this_block.port('dir').width ~= 1);
      this_block.setError('Input data type for port "dir" must have width=1.');
    end

    this_block.port('dir').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../master.vhd');
  this_block.addFile('../contador_sinc.vhd');
  this_block.addFile('../divisor.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

